name: 'Setup Node.js'
description: 'Setup Node.js, checkout code, and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: npm ci --prefer-offline --no-audit

