name: 'Firebase Emulators'
description: 'Start or stop Firebase emulators with proper error handling and process management'

inputs:
  action:
    description: 'Action to perform: start or stop'
    required: true
  project-id:
    description: 'Firebase project ID'
    required: false
    default: 'demo-test'
  max-attempts:
    description: 'Maximum attempts to wait for emulator UI'
    required: false
    default: '30'
  emulator-ui-port:
    description: 'Port for Firebase Emulator UI'
    required: false
    default: '4000'

runs:
  using: 'composite'
  steps:
    - name: Start Firebase Emulators
      if: inputs.action == 'start'
      shell: bash
      run: |
        echo "Starting Firebase emulators..."
        
        # Start emulators in background with explicit project
        # Use --project flag to avoid any project detection issues
        npx firebase emulators:start --only auth,firestore --project ${{ inputs.project-id }} > emulator.log 2>&1 &
        BACKGROUND_PID=$!
        echo "Background process started with PID: $BACKGROUND_PID"
        
        # Give emulators minimal time to initialize
        sleep 2
        
        # Check if background process is still running
        if ! kill -0 $BACKGROUND_PID 2>/dev/null; then
          echo "✗ Background process died immediately. Logs:"
          cat emulator.log
          exit 1
        fi
        
        # Find the actual firebase/java process PID (more reliable)
        # Firebase emulators spawn Java processes, so we need to find those
        sleep 1
        EMULATOR_PID=$(ps aux | grep -E "[j]ava.*firebase" | awk '{print $2}' | head -1)
        if [ -z "$EMULATOR_PID" ]; then
          # Fallback: try to find any firebase process
          EMULATOR_PID=$(ps aux | grep -E "[f]irebase" | awk '{print $2}' | head -1)
        fi
        
        if [ -z "$EMULATOR_PID" ]; then
          echo "✗ Failed to find emulator process. Logs:"
          cat emulator.log
          exit 1
        fi
        
        echo "✓ Found emulator process with PID: $EMULATOR_PID"
        echo "EMULATOR_PID=$EMULATOR_PID" >> $GITHUB_ENV
        
        # Wait for emulator UI to be ready (this indicates all emulators are up)
        echo "Waiting for Firebase emulators to start..."
        MAX_ATTEMPTS=${{ inputs.max-attempts }}
        ATTEMPT=0
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          # Check if process is still running first
          if ! kill -0 $EMULATOR_PID 2>/dev/null; then
            echo "✗ Emulator process (PID: $EMULATOR_PID) died. Logs:"
            cat emulator.log
            exit 1
          fi
          
          # Check if emulator UI is ready
          if curl -f -s http://localhost:${{ inputs.emulator-ui-port }} > /dev/null 2>&1; then
            echo "✓ Firebase emulators are ready! (took ~$((ATTEMPT * 1))s)"
            break
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
          
          # Show progress every 10 attempts
          if [ $((ATTEMPT % 10)) -eq 0 ]; then
            echo "  Attempt $ATTEMPT/$MAX_ATTEMPTS: Still waiting..."
          fi
          
          if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
            echo "✗ Emulators failed to start within timeout. Logs:"
            cat emulator.log
            exit 1
          fi
          
          sleep 1
        done
        
        echo "✓ Emulator startup complete"

    - name: Stop Firebase Emulators
      if: inputs.action == 'stop'
      shell: bash
      run: |
        echo "Stopping Firebase emulators..."
        # Try to kill by PID if available
        if [ -n "$EMULATOR_PID" ]; then
          echo "Killing emulator process PID: $EMULATOR_PID"
          kill $EMULATOR_PID 2>/dev/null || true
          sleep 1
        fi
        # Kill any remaining firebase/java processes
        pkill -f "firebase emulators" || true
        pkill -f "java.*firebase" || true
        # Wait a moment for processes to terminate
        sleep 1
        # Verify cleanup
        if pgrep -f "firebase emulators" > /dev/null; then
          echo "Warning: Some emulator processes may still be running"
        else
          echo "✓ All emulator processes stopped"
        fi

