name: 'Test Environment Variables'
description: 'Set up test environment variables for E2E tests (DEPRECATED: Use setup-env-vars with context=test instead)'

inputs:
  project-id:
    description: 'Firebase project ID'
    required: false
    default: 'demo-test'
  base-url:
    description: 'Base URL for E2E tests'
    required: false
    default: 'http://localhost:3000'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables (using unified action)
      uses: ./.github/actions/setup-env-vars
      with:
        context: 'test'
        project-id: ${{ inputs.project-id }}
        base-url: ${{ inputs.base-url }}
      # NOTE: FIREBASE_ADMIN_CLIENT_EMAIL and FIREBASE_ADMIN_PRIVATE_KEY are NOT set in test environment.
      # Firebase Admin SDK uses minimal config (no credentials) when connecting to emulators in test mode.
      # This is the secure approach - no credentials are needed or exposed in CI/CD.
      # See lib/firebase-admin.ts for implementation details.

