name: 'Test Environment Variables'
description: 'Set up test environment variables for E2E tests'

inputs:
  project-id:
    description: 'Firebase project ID'
    required: false
    default: 'demo-test'
  base-url:
    description: 'Base URL for E2E tests'
    required: false
    default: 'http://localhost:3000'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "E2E_TEST=true" >> $GITHUB_ENV
        echo "NODE_ENV=test" >> $GITHUB_ENV
        echo "CI=true" >> $GITHUB_ENV
        echo "E2E_BASE_URL=${{ inputs.base-url }}" >> $GITHUB_ENV
        echo "FIREBASE_AUTH_EMULATOR_HOST=localhost:9099" >> $GITHUB_ENV
        echo "FIRESTORE_EMULATOR_HOST=localhost:8080" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:9099" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST=localhost:8080" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_API_KEY=test-api-key" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=localhost" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ inputs.project-id }}" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ inputs.project-id }}.appspot.com" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=123456789" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_FIREBASE_APP_ID=1:123456789:web:test" >> $GITHUB_ENV
        echo "FIREBASE_ADMIN_PROJECT_ID=${{ inputs.project-id }}" >> $GITHUB_ENV
        echo "FIREBASE_ADMIN_CLIENT_EMAIL=test@example.com" >> $GITHUB_ENV
        # Private key with escaped newlines for GITHUB_ENV
        printf 'FIREBASE_ADMIN_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC\\n-----END PRIVATE KEY-----\\n' >> $GITHUB_ENV

