name: 'Run E2E Tests'
description: 'Run E2E tests with proper error handling and debugging'

inputs:
  test-paths:
    description: 'Space-separated test paths'
    required: true
  suite-name:
    description: 'Name of the test suite'
    required: true
  timeout:
    description: 'Test timeout in milliseconds'
    required: false
    default: '300000'

runs:
  using: 'composite'
  steps:
    - name: Prepare test environment
      shell: bash
      run: |
        echo "Running tests for: ${{ inputs.suite-name }}"
        echo "Test paths: ${{ inputs.test-paths }}"
        echo ""
        echo "Environment variables:"
        env | grep -E "(E2E_|CI|NODE_ENV|FIREBASE_|NEXT_PUBLIC_)" | sort
        echo ""
        
        echo "Verifying Playwright installation:"
        npx playwright --version || echo "Playwright not found"
        echo ""
        
        echo "Checking test files exist:"
        TEST_PATHS_ARRAY=()
        for path in ${{ inputs.test-paths }}; do
          path=$(echo "$path" | xargs)
          [ -z "$path" ] && continue
          if [ -d "$path" ] || [ -f "$path" ]; then
            echo "✓ Found: $path"
            TEST_PATHS_ARRAY+=("$path")
          else
            echo "✗ Not found: $path"
          fi
        done
        
        if [ ${#TEST_PATHS_ARRAY[@]} -eq 0 ]; then
          echo "ERROR: No test paths found!"
          exit 1
        fi
        
        # Store validated paths for next step (space-separated, properly quoted)
        printf -v TEST_PATHS_STR '%q ' "${TEST_PATHS_ARRAY[@]}"
        echo "TEST_PATHS_STR=$TEST_PATHS_STR" >> $GITHUB_ENV

    - name: Run Tests
      shell: bash
      run: |
        # Safely reconstruct array from stored string
        read -ra TEST_PATHS_ARRAY <<< "$TEST_PATHS_STR"
        
        echo "Starting tests with paths: ${TEST_PATHS_ARRAY[*]}"
        echo ""
        echo "Note: Playwright will automatically start the Next.js dev server via webServer configuration"
        echo "This may take up to 2 minutes for the first build..."
        
        set -o pipefail
        PLAYWRIGHT_TIMEOUT=${{ inputs.timeout }} npx playwright test "${TEST_PATHS_ARRAY[@]}" --timeout=60000 2>&1 | tee test-output.log
        TEST_EXIT_CODE=${PIPESTATUS[0]}
        
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo ""
          echo "=========================================="
          echo "Tests failed with exit code: $TEST_EXIT_CODE"
          echo "=========================================="
          cat test-output.log || true
          exit $TEST_EXIT_CODE
        fi

    - name: Debug on failure
      if: failure()
      shell: bash
      run: |
        echo "=========================================="
        echo "Service Health Status:"
        echo "=========================================="
        echo "Next.js server:"
        if curl -f -s http://localhost:3000 > /dev/null 2>&1; then
          echo "✓ Running on port 3000"
        else
          echo "✗ NOT running on port 3000"
          lsof -i :3000 || echo "Port 3000 is not in use"
        fi
        echo ""
        echo "Firebase Emulators:"
        curl -f -s http://localhost:4000 > /dev/null 2>&1 && echo "✓ UI running" || echo "✗ UI NOT running"
        nc -z localhost 9099 2>/dev/null && echo "✓ Auth emulator port open" || echo "✗ Auth emulator port closed"
        nc -z localhost 8080 2>/dev/null && echo "✓ Firestore emulator port open" || echo "✗ Firestore emulator port closed"
        echo ""
        echo "Process Status:"
        ps aux | grep -E "[n]ext|node.*dev" || echo "No Next.js processes"
        ps aux | grep -E "[f]irebase|[j]ava.*firebase" || echo "No Firebase processes"
        echo ""
        echo "Environment variables check:"
        echo "  E2E_TEST=$E2E_TEST"
        echo "  CI=$CI"
        echo "  NODE_ENV=$NODE_ENV"
        echo "  FIREBASE_AUTH_EMULATOR_HOST=$FIREBASE_AUTH_EMULATOR_HOST"
        echo "  FIRESTORE_EMULATOR_HOST=$FIRESTORE_EMULATOR_HOST"
        echo "  NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID"

