name: 'Run E2E Tests'
description: 'Run E2E tests with proper error handling and debugging'

inputs:
  test-paths:
    description: 'Space-separated test paths'
    required: true
  suite-name:
    description: 'Name of the test suite'
    required: true
  shard:
    description: 'Shard number (e.g., 1)'
    required: false
  shards:
    description: 'Total number of shards (e.g., 2)'
    required: false
  grep:
    description: 'Test tag filter (e.g., @regression)'
    required: false
  timeout:
    description: 'Test timeout in milliseconds (should account for webServer startup ~180s + test execution)'
    required: false
    default: '240000'

runs:
  using: 'composite'
  steps:
    - name: Prepare test environment
      shell: bash
      run: |
        echo "Running tests for: ${{ inputs.suite-name }}"
        echo "Test paths: ${{ inputs.test-paths }}"
        echo ""
        echo "Environment variables (non-sensitive only):"
        # Filter out variables with sensitive names (API_KEY, AUTH_TOKEN, etc.)
        # Note: This shows test environment values only - production secrets are never exposed
        env | grep -E "(E2E_|CI|NODE_ENV|FIREBASE_|NEXT_PUBLIC_)" | \
          grep -vE "(PRIVATE_KEY|SECRET|PASSWORD|CREDENTIAL|API_KEY|AUTH_TOKEN)" | sort
        echo ""
        
        echo "Verifying Playwright installation:"
        npx playwright --version || echo "Playwright not found"
        echo ""
        
        echo "Checking test files exist:"
        TEST_PATHS_ARRAY=()
        for path in ${{ inputs.test-paths }}; do
          path=$(echo "$path" | xargs)
          [ -z "$path" ] && continue
          if [ -d "$path" ] || [ -f "$path" ]; then
            echo "✓ Found: $path"
            TEST_PATHS_ARRAY+=("$path")
          else
            echo "✗ Not found: $path"
          fi
        done
        
        if [ ${#TEST_PATHS_ARRAY[@]} -eq 0 ]; then
          echo "ERROR: No test paths found!"
          exit 1
        fi
        
        # Store validated paths in a file for the next step
        # This avoids issues with special characters and spaces in GITHUB_ENV
        printf '%s\n' "${TEST_PATHS_ARRAY[@]}" > /tmp/test_paths.txt
        echo "TEST_PATHS_FILE=/tmp/test_paths.txt" >> $GITHUB_ENV

    - name: Run Tests
      shell: bash
      run: |
        # Read paths from file into array
        if [ -f "$TEST_PATHS_FILE" ]; then
          mapfile -t TEST_PATHS_ARRAY < "$TEST_PATHS_FILE"
        else
          echo "ERROR: Test paths file not found: $TEST_PATHS_FILE"
          exit 1
        fi
        
        echo "Starting tests with paths: ${TEST_PATHS_ARRAY[*]}"
        echo ""
        echo "Note: Playwright will automatically start the Next.js dev server via webServer configuration"
        echo "This may take up to 2 minutes for the first build..."
        
        # Build additional arguments array
        ADDITIONAL_ARGS=()
        
        # Add shard arguments if provided
        if [ -n "${{ inputs.shard }}" ] && [ -n "${{ inputs.shards }}" ]; then
          ADDITIONAL_ARGS+=("--shard=${{ inputs.shard }}/${{ inputs.shards }}")
          echo "Using sharding: --shard=${{ inputs.shard }}/${{ inputs.shards }}"
        fi
        
        # Add grep arguments if provided
        if [ -n "${{ inputs.grep }}" ]; then
          ADDITIONAL_ARGS+=("--grep=${{ inputs.grep }}")
          echo "Using grep filter: --grep=${{ inputs.grep }}"
        fi
        
        # Add timeout argument
        ADDITIONAL_ARGS+=("--timeout=${{ inputs.timeout }}")
        
        set -o pipefail
        # Use the timeout input for test timeout (default 240000ms = 4 minutes)
        # This gives enough time for webServer startup (~180s) and test execution
        npx playwright test "${TEST_PATHS_ARRAY[@]}" "${ADDITIONAL_ARGS[@]}" 2>&1 | tee test-output.log
        TEST_EXIT_CODE=${PIPESTATUS[0]}
        
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo ""
          echo "=========================================="
          echo "Tests failed with exit code: $TEST_EXIT_CODE"
          echo "=========================================="
          # Sanitize log output to remove sensitive data
          ERROR_DETAILS=""
          if [ -f "test-output.log" ]; then
            ERROR_DETAILS=$(sed -E 's/(PRIVATE_KEY|SECRET|PASSWORD|CREDENTIAL|API_KEY|AUTH_TOKEN)=[^[:space:]]*/&=[REDACTED]/gi' test-output.log | \
            sed -E 's/-----BEGIN[^-]*-----/-----BEGIN [REDACTED]-----/gi' | \
            sed -E 's/-----END[^-]*-----/-----END [REDACTED]-----/gi' | tail -50)
            echo "$ERROR_DETAILS"
          fi
          
          # Export error details for error handler
          echo "TEST_ERROR_DETAILS<<EOF" >> $GITHUB_ENV
          echo "$ERROR_DETAILS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          exit $TEST_EXIT_CODE
        fi

    - name: Handle test failure
      if: failure()
      uses: ./.github/actions/error-handler
      with:
        error-type: 'test_timeout'
        error-context: 'Test suite ${{ inputs.suite-name }} failed'
        error-details: ${{ env.TEST_ERROR_DETAILS || 'Check test-output.log for details' }}

    - name: Debug on failure
      if: failure()
      shell: bash
      run: |
        echo "=========================================="
        echo "Service Health Status:"
        echo "=========================================="
        echo "Next.js server:"
        if curl -f -s http://localhost:3000 > /dev/null 2>&1; then
          echo "✓ Running on port 3000"
        else
          echo "✗ NOT running on port 3000"
          lsof -i :3000 || echo "Port 3000 is not in use"
        fi
        echo ""
        echo "Firebase Emulators:"
        curl -f -s http://localhost:4000 > /dev/null 2>&1 && echo "✓ UI running" || echo "✗ UI NOT running"
        nc -z localhost 9099 2>/dev/null && echo "✓ Auth emulator port open" || echo "✗ Auth emulator port closed"
        nc -z localhost 8081 2>/dev/null && echo "✓ Firestore emulator port open" || echo "✗ Firestore emulator port closed"
        echo ""
        echo "Process Status:"
        ps aux | grep -E "[n]ext|node.*dev" || echo "No Next.js processes"
        ps aux | grep -E "[f]irebase|[j]ava.*firebase" || echo "No Firebase processes"
        echo ""
        echo "Environment variables check (sanitized):"
        echo "  E2E_TEST=$E2E_TEST"
        echo "  CI=$CI"
        echo "  NODE_ENV=$NODE_ENV"
        echo "  FIREBASE_AUTH_EMULATOR_HOST=$FIREBASE_AUTH_EMULATOR_HOST"
        echo "  FIRESTORE_EMULATOR_HOST=$FIRESTORE_EMULATOR_HOST"
        # Sanitize project ID and other potentially sensitive values
        if [ -n "$NEXT_PUBLIC_FIREBASE_PROJECT_ID" ]; then
          echo "  NEXT_PUBLIC_FIREBASE_PROJECT_ID=[SET]"
        else
          echo "  NEXT_PUBLIC_FIREBASE_PROJECT_ID=[NOT SET]"
        fi
        # Don't print API keys or tokens even if they're test values
        echo "  NEXT_PUBLIC_FIREBASE_API_KEY=[REDACTED]"
        echo "  (Other sensitive variables are set but not displayed)"

