name: 'Load CI Configuration'
description: 'Load and validate centralized CI/CD configuration, export as environment variables'

inputs:
  config-path:
    description: 'Path to configuration file'
    required: false
    default: '.github/config/ci-config.yml'

runs:
  using: 'composite'
  steps:
    - name: Validate config file exists
      shell: bash
      run: |
        if [ ! -f "${{ inputs.config-path }}" ]; then
          echo "ERROR: Configuration file not found at ${{ inputs.config-path }}"
          exit 1
        fi
        echo "✓ Configuration file found"

    - name: Load and export configuration
      shell: bash
      run: |
        # Make script executable
        chmod +x "${{ github.action_path }}/load-config.js"
        
        # Run the config loader script
        node "${{ github.action_path }}/load-config.js" "${{ inputs.config-path }}"
        
        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to load configuration"
          exit 1
        fi
