name: 'Upload Test Artifacts'
description: 'Upload Playwright test results and screenshots'

inputs:
  artifact-name:
    description: 'Base name for artifacts'
    required: true
  report-retention-days:
    description: 'Days to retain test reports'
    required: false
    default: '30'
  screenshot-retention-days:
    description: 'Days to retain screenshots'
    required: false
    default: '7'

runs:
  using: 'composite'
  steps:
    - name: Compress test results
      if: always()
      shell: bash
      run: |
        if [ -d "playwright-report" ] && [ "$(ls -A playwright-report 2>/dev/null)" ]; then
          echo "Compressing test results..."
          tar -czf test-results-${{ inputs.artifact-name }}.tar.gz playwright-report/ || true
          echo "Compression complete"
        else
          echo "No test results to compress"
        fi

    - name: Compress test screenshots
      if: failure()
      shell: bash
      run: |
        if [ -d "test-results" ] && [ "$(ls -A test-results 2>/dev/null)" ]; then
          echo "Compressing test screenshots..."
          tar -czf test-screenshots-${{ inputs.artifact-name }}.tar.gz test-results/ || true
          echo "Compression complete"
        else
          echo "No screenshots to compress"
        fi

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ inputs.artifact-name }}
        path: |
          playwright-report/
          test-results-${{ inputs.artifact-name }}.tar.gz
        retention-days: ${{ inputs.report-retention-days }}
        if-no-files-found: ignore

    - name: Upload test screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots-${{ inputs.artifact-name }}
        path: |
          test-results/
          test-screenshots-${{ inputs.artifact-name }}.tar.gz
        retention-days: ${{ inputs.screenshot-retention-days }}
        if-no-files-found: ignore

